### ISSUE TITLE
Console warning for missing source map contenteditable.vue.map

### ISSUE THREAD

**Issue by madebyfabian** [hl037/vue-contenteditable#12]
Hello there,
the plugin works like a charm, so first of all, thanks for making it! I am using it in the 1.0.2 version, since I am using Vue 2.
As I installed the plugin, I always get this console warning:
```
DevTools failed to load source map: Could not load content for http://localhost:8080/contenteditable.vue.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
it seems that it does want to load a sourcemap to it, what does not make sense since I installed the plugin regularly via npm and it therefore should not want to load any sourcemaps since it's in prod mode.
Would be great if you could look into it, thanks!

**Comment by hl037** [comment]
Hi,
I think it's the Vue DevTools that tries to get a source map to enable debugging. The source map may not be present /served if not compiled from sources. Try with the Vue Dev tools disabled to confirm it. If the message does not appear then I think you are good.
I'm in hollydays currently so I won't be able to look into it before 3 weeks...

**Comment by madebyfabian** [comment]
Hey there, can't test it since I'm not using the package anymore. Will close this ticket for now, since it doesn't affect the functionality of the plugin in anyway.

**Comment by scil** [comment]
just delete `sourceMappingURL=contenteditable.vue.map` from `vue-contenteditable/dist/contenteditable.esm.js`

then produce a patch file

**Comment by hl037** [comment]
I think

**Comment by hl037** [comment]
No answer, so I believe it's not a problem anymore
