### ISSUE TITLE
Getting “A module cannot have multiple default exports” error when  building

### ISSUE THREAD

**Issue by mgiraldo** [hl037/vue-contenteditable#17]
The types file has two default exports and this is not supported by TypeScript:

https://github.com/hl037/vue-contenteditable/blob/2b0dc16ba6d77193a717e1b97ac6b6007d07ab03/index.d.ts#L4

https://github.com/hl037/vue-contenteditable/blob/2b0dc16ba6d77193a717e1b97ac6b6007d07ab03/index.d.ts#L41

This could be addressed by making only one of them the default export?

**Comment by hl037** [comment]
Indeed...
What is even weirder is that it's auto-generated. But It's been quite some time I haven't touched the project, and maybe there was some bug corrected dts-bundle.

I will look into it when I get some times. In the mean time, I think you can safely remove the 2 first lines of this file

**Comment by mgiraldo** [comment]
yeah. i had to remove the package, though, because my build process does some build processes automatically which prevented me from just including the altered file.

**Comment by hl037** [comment]
I am upgrading the package to using vite instead of vue-cli. Hopefully, this bug will disappear then...

**Comment by hl037** [comment]
Should be fixed in v4.0.0
