### ISSUE TITLE
are there any types for TypeScript support?

### ISSUE THREAD

**Issue by JakubKoralewski** [hl037/vue-contenteditable#2]
```
Could not find a declaration file for module 'vue-contenteditable'. '<jakub_koralewski_node_modules_path>/contenteditable.umd.js' implicitly has an 'any' type.
  Try `npm install @types/vue-contenteditable` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-contenteditable';`ts(7016)
```

**Comment by hl037** [comment]
No, there are no support for TypeScript right now, since I don't know yet this language.
However, if you know how to do it, feel free to make a pull request, or to give mi some starting point to at least make it compatible with ts :)

**Comment by hl037** [comment]
Since Vue is now developped in typescript, and it seems to be the feature, the next upgrade will be coded with typescript. it should come during this week

**Comment by JakubKoralewski** [comment]
> However, if you know how to do it, feel free to make a pull request, or to give mi some starting point to at least make it compatible with ts :)

I'm sorry, I missed this reply 😢 Glad to hear it's going to happen though! :tada:

**Comment by hl037** [comment]
Updated
