### ISSUE TITLE
Propose function to unwrap breaks

### ISSUE THREAD

**Issue by andyjamesn** [hl037/vue-contenteditable#24]
When using HTML and you press enter twice contenteditable outputs

<div><br></div>

When <br> should suffice

I would like to propose a small improvement

```js
function unwrapBreaks(innerHTML: string) {
    return innerHTML.replaceAll('<div><br></div>', '<br />');
}
```

Then change (I think this is the correct place to do this)

```js
function currentContent() {
    return props.noHtml
      ? element.value!.innerText
      : element.value!.innerHTML;
}
```

to

```js
function currentContent() {
    return props.noHtml
      ? element.value!.innerText
      : unwrapBreaks(element.value!.innerHTML); 
}
```

This will remove the div's wrapping around breaks.

**Comment by hl037** [comment]
Hi, 
I am very sorry for the late answer, I was busy like hell last week...

Does it happen when you do <kbd>Shift</kbd>+<kbd>Enter</kbd>" ?

Normally, as for nearly all wysiwyg editors, pressing <kbd>Enter</kbd> starts a new paragraph (actually my plugin is not responsable for the `<div/>` addition, and btw, I think navigators may be wrong not to insert `<p/>` instead...)

If shift+enter does not insert the `<div>`, I think we should consider it a feature. Adding such post filter could actually lead to unexpected behaviors I think...

**Comment by hl037** [comment]
I have tested on the sample, I get the expected behavior that with enter, it inserts a div+br, and with shift-enter, it just inserts a br

**Comment by hl037** [comment]
No response for 2 month, an no further discussion => closing now
