### ISSUE TITLE
failed to mount component

### ISSUE THREAD

**Issue by HawtinZeng** [hl037/vue-contenteditable#31]
In vue-cli@4.5.8,vue-contenteditable@1.0.2, failed to mount component: template or render function not defined found in Contenteditable

**Comment by gfrancis86** [comment]
what is the fix for this?

**Comment by hl037** [comment]
I'm sorry, i can't do much atm, becaucause i'm locked off of my github
account thanks to 2fa >.< (i'm respounding by mail)

Le ven. 5 janv. 2024 à 19:39, Griselda Shelton ***@***.***> a
écrit :

**Comment by HawtinZeng** [comment]
> what is the fix for this?

I write a editable component by myself, just use contenteditable attribute of a div, @blur event, and some css style, it's easy, we can add many custom styles
