### ISSUE TITLE
How to access updated value in parent components?

### ISSUE THREAD

**Issue by saileshkush95** [hl037/vue-contenteditable#8]
Actually I'm new to vue, can please help me to access updated value in parent components so that i can use this value to update in the server.

Here is my code snippets.

```
      <text-editor
        tag="li"
        v-for="page in getNavLink"
        :key="page.id"
        class="border-4 border-light-blue-500 p-2 m-2 border-opacity-25 flex"
        :value="page.title"
        :noNL="true"
        @focus="focus"
        @returned="updatePage"
        @click="updateId(page.id)"
      >
      </text-editor>
```

**Comment by hl037** [comment]
You should use v-model instead of :value, and use it as a usual input tag. At the moment, it seems there is a bug with Vue 3 (I didn't have time yet to port it to Vue 3) : #6

**Comment by hl037** [comment]
The problem comes from Vue 3 having changed the v-model protocol. I am porting it to vu 3 and typescript, stay tuned :)

**Comment by hl037** [comment]
Fixed in the latest update
